name: Terraform Deployment
on: workflow_dispatch

jobs:
  terraform:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 1.0.10
          terraform_version: 1.3.5
      # - name: Terrafrom Format
      #   id: format 
      #   run: |
      #     cd terraform
      #     terraform fmt -check
      - name: Terraform version
        run: terraform version
      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan
      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve